import { ILayout } from '@/interfaces';
import * as React from 'react';



import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "HoatHinhOnline",
    description: "Generated by create next app",
};

export default function EntityLayout({
    children,
}: React.PropsWithChildren<ILayout>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
            </body>
        </html>
    );
}